/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {

    val greeting: String
        get() {
            return "Hello World!" + "\nSecret message: ${getSecret()}"
        }

    private fun getSecret(): String {
        return System.getenv("SECRET_MESSAGE")
    }
}

fun main() {
    println(App().greeting)
}
