/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.gradle.api.Project
import org.gradle.api.Plugin


class EnvValidatorPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        val extension = project.extensions.create("envValidator", EnvValidatorExtension::class.java)

        // Set meaningful defaults
        extension.ignoreSpringDefaults.convention(true) // Default to lenient (if default value exists, don't fail)

        // Default scan targets: main resources and main java/kotlin source
        val defaultScanPath = project.files("src/main/resources", "src/main/java", "src/main/kotlin")
        extension.directoriesToScan.setFrom(defaultScanPath)

        project.tasks.register("validateEnvironment", ValidateEnvTask::class.java) { it
            it.group = "verification"
            it.description = "Scans project for environment variable usage and verifies they are set."

            it.directoriesToScan.set(extension.directoriesToScan)
            it.ignoreVariables.set(extension.ignoreVariables)
            it.ignoreSpringDefaults.set(extension.ignoreSpringDefaults)
        }
    }
}