/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.example.env-validator' plugin.
 */
class EnvValidatorPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.example.env-validator")

        // Verify the result
        assertNotNull(project.tasks.findByName("validateEnvironment"))
    }
}
